services:
  db:
    image: postgres:16
    container_name: pingmebot-postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data

  app:
    build: .
    container_name: pingmebot-app
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  worker:
    build: .
    restart: unless-stopped
    depends_on:
      - db
      - redis
    env_file:
      - .env
    volumes:
      - .:/app
    command: celery -A app.celery_app:celery_app worker -l info


volumes:
  pg_data:
  redis_data:
