"""remove task.remind_at, add task_reminder relationship

Revision ID: 1446430576be
Revises: 142e53485835
Create Date: 2025-12-26 15:46:25.884866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1446430576be'
down_revision: Union[str, Sequence[str], None] = '142e53485835'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('remind_at', sa.DateTime(), nullable=False),
    sa.Column('is_sent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_reminders_task_id'), 'task_reminders', ['task_id'], unique=False)
    op.drop_column('tasks', 'remind_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('remind_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_task_reminders_task_id'), table_name='task_reminders')
    op.drop_table('task_reminders')
    # ### end Alembic commands ###
