"""add unique constraint to task_reminders

Revision ID: e4505e821e13
Revises: 1446430576be
Create Date: 2026-02-24 15:15:19.029784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4505e821e13'
down_revision: Union[str, Sequence[str], None] = '1446430576be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_task_reminders_task_id_remind_at', 'task_reminders', ['task_id', 'remind_at'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_task_reminders_task_id_remind_at', 'task_reminders', type_='unique')
    # ### end Alembic commands ###
